# Generated by Django 2.1.7 on 2019-03-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedVideoTestDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=20)),
                ('start', models.FloatField(max_length=10)),
                ('duration', models.FloatField(max_length=10)),
                ('user_id', models.CharField(max_length=15)),
                ('video_duration', models.FloatField(max_length=20)),
                ('is_last', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'PersonalizedVideoTestDataset',
            },
        ),
        migrations.CreateModel(
            name='PersonalizedVideoTrainingDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=20)),
                ('start', models.FloatField(max_length=10)),
                ('duration', models.FloatField(max_length=10)),
                ('user_id', models.CharField(max_length=15)),
                ('video_duration', models.FloatField(max_length=20)),
                ('is_last', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'PersonalizedVideoTrainingDataset',
            },
        ),
    ]
