# Generated by Django 2.1.7 on 2019-03-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HighlightDetectionApp', '0001_Added video dataset models'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideoDownloadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=20, unique=True)),
                ('downloaded', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'YoutubeVideoDownloadStatus',
            },
        ),
    ]
