# Generated by Django 2.1.7 on 2019-03-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HighlightDetectionApp', '0002_youtube_vedio_download_status_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizedvideotestdataset',
            name='youtube_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='personalizedvideotrainingdataset',
            name='youtube_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='youtubevideodownloadstatus',
            name='youtube_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
