# Generated by Django 2.1.7 on 2019-03-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HighlightDetectionApp', '0003_added_db_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideoDownloadTrainStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('downloaded', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'YoutubeVideoDownloadTrainStatus',
            },
        ),
        migrations.RenameModel(
            old_name='YoutubeVideoDownloadStatus',
            new_name='YoutubeVideoDownloadTestStatus',
        ),
        migrations.AlterModelTable(
            name='youtubevideodownloadteststatus',
            table='YoutubeVideoDownloadTestStatus',
        ),
    ]
