# Generated by Django 2.1.7 on 2019-03-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HighlightDetectionApp', '0004_separate_download_status_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMetaDataInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.CharField(default='', max_length=400)),
                ('title', models.CharField(default='', max_length=400)),
                ('alt_title', models.CharField(default='', max_length=400)),
                ('thumbnail_link', models.CharField(default='', max_length=100)),
                ('category', models.CharField(max_length=100, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'VideoMetadataInformation',
            },
        ),
    ]
