# Generated by Django 2.1.7 on 2019-03-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HighlightDetectionApp', '0005_added_metadata_info_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometadatainfo',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
