# Generated by Django 2.1.7 on 2019-03-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HighlightDetectionApp', '0006_added_rating_to_metadata_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometadatainfo',
            name='stream',
            field=models.CharField(default='', max_length=20),
        ),
    ]
