# Generated by Django 2.1.7 on 2019-03-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HighlightDetectionApp', '0007_added_stream_attribute_to_metadata_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideodownloadteststatus',
            name='message',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='youtubevideodownloadtrainstatus',
            name='message',
            field=models.CharField(default='', max_length=100),
        ),
    ]
