# Generated by Django 2.1.7 on 2019-03-05 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HighlightDetectionApp', '0008_added_message_attribute_to_download_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videometadatainfo',
            name='alt_title',
        ),
    ]
