# Generated by Django 2.1.7 on 2019-03-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HighlightDetectionApp', '0010_increased_error_message_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videometadatainfo',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='videometadatainfo',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
