# Generated by Django 2.1.7 on 2019-03-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HighlightDetectionApp', '0011_increased_description_title_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videometadatainfo',
            name='description',
            field=models.CharField(default='', max_length=8000),
        ),
    ]
